# pyreportjasper CI pipeline
trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - .azure/build.yml
    - docs/*
    - setup.py
    - setupext/*
    - pyreportjasper/*
    - tests/*

jobs:
- job: Documentation
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - template: scripts/documentation.yml

- job: Test
  # dependsOn: Deps
  strategy:
    matrix:
      linux-3.8:
        imageName: "ubuntu-latest"
        python.version: '3.8'
      linux-3.9:
        imageName: "ubuntu-latest"
        python.version: '3.9'
      linux-3.10:
        imageName: "ubuntu-latest"
        python.version: '3.10'
      linux-3.11:
        imageName: "ubuntu-latest"
        python.version: '3.11'
      # linux-3.12:
      #   imageName: "ubuntu-latest"
      #   python.version: '3.12'
      windows-3.8:
        imageName: "windows-2019"
        python.version: '3.8'
      windows-3.9:
        imageName: "windows-2019"
        python.version: '3.9'
      windows-3.10:
        imageName: "windows-2019"
        python.version: '3.10'
      windows-3.11:
        imageName: "windows-2019"
        python.version: '3.11'
      # windows-3.12:
      #   imageName: "windows-2019"
      #   python.version: '3.12'
      mac-3.9:
        imageName: "macos-11"
        python.version: '3.9'

  pool:
    vmImage: $(imageName)
  # steps:
  # # - template: scripts/deps.yml
  # # - template: scripts/test.yml
